# Generated by Django 4.0 on 2022-07-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchlist', '0001_initial'),
        ('data', '0001_initial'),
        ('website', '0001_initial'),
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watchlists', to='website.account'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_currency', to='data.currency'),
        ),
        migrations.AddField(
            model_name='cryptoportfolio',
            name='coins',
            field=models.ManyToManyField(blank=True, related_name='portfolio_coins', through='watchlist.Amounts', to='crypto.Cryptocurrency'),
        ),
        migrations.AddField(
            model_name='cryptoportfolio',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_portfolio', to='website.account'),
        ),
        migrations.AddField(
            model_name='cryptoportfolio',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_currency', to='data.currency'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_coin', to='crypto.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_portfolio', to='watchlist.cryptoportfolio'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_source', to='crypto.cryptoexchange'),
        ),
    ]
