# Generated by Django 4.0 on 2022-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_ticker_asset_class_ticker_base_full_name_and_more'),
        ('watchlist', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='currency',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='tickers',
            field=models.ManyToManyField(blank=True, related_name='watchlist_coins', to='markets.Ticker'),
        ),
    ]
