# Generated by Django 4.0 on 2022-07-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset_class', models.CharField(blank=True, max_length=32, null=True)),
                ('base', models.CharField(max_length=16)),
                ('base_full_name', models.CharField(blank=True, max_length=128, null=True)),
                ('quote_asset_class', models.CharField(blank=True, max_length=32, null=True)),
                ('quote', models.CharField(max_length=16)),
                ('quote_full_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=64)),
                ('daily_delta', models.FloatField(blank=True, null=True)),
                ('daily_pct_delta', models.FloatField(blank=True, null=True)),
                ('daily_vol', models.FloatField(blank=True, null=True)),
                ('daily_low', models.FloatField(blank=True, null=True)),
                ('daily_high', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_quote', to='markets.ticker')),
            ],
        ),
    ]
