# Generated by Django 4.0 on 2022-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='asset_class',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='base_full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='daily_pct_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='quote_full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
