# Generated by Django 4.0 on 2022-07-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_ticker_asset_class_ticker_base_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='mid',
        ),
    ]
