# Generated by Django 4.0 on 2022-04-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='selector',
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='website',
            name='selectors',
            field=models.ManyToManyField(blank=True, related_name='website_selector', to='news.Selector'),
        ),
    ]
