# Generated by Django 4.0 on 2022-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
