# Generated by Django 4.0 on 2022-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_log_message_alter_log_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='table',
        ),
        migrations.AddField(
            model_name='log',
            name='source',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
