# Generated by Django 4.0 on 2022-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_update_remove_log_table_log_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='table',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
