# Generated by Django 4.0 on 2022-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('coins', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('categories', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EconEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('zone', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=8)),
                ('importance', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('actual', models.FloatField(null=True)),
                ('forecast', models.FloatField(null=True)),
                ('previous', models.CharField(max_length=16)),
            ],
        ),
    ]
