# Generated by Django 4.0 on 2022-07-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('asset_class', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('group', models.CharField(blank=True, choices=[(0, 'metals'), (1, 'softs'), (2, 'meats'), (3, 'energy'), (4, 'grains')], max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_issuer', to='data.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='currency_country', to='data.Currency'),
        ),
    ]
