# Generated by Django 4.0 on 2022-04-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('website', '0001_initial'),
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_pubkey', to='website.account'),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='pub_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub_privkey', to='crypto.publickey'),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_privkey', to='website.account'),
        ),
        migrations.AddField(
            model_name='cryptowatchlist',
            name='coins',
            field=models.ManyToManyField(blank=True, related_name='watchlist_coins', through='crypto.Amounts', to='crypto.Cryptocurrency'),
        ),
        migrations.AddField(
            model_name='cryptowatchlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watchlists', to='website.account'),
        ),
        migrations.AddField(
            model_name='cryptowatchlist',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_currency', to='data.currency'),
        ),
        migrations.AddField(
            model_name='cryptowatchlist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='watchlist_followers', to='website.Account'),
        ),
        migrations.AddField(
            model_name='cryptoexchange',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='exchange_countries', to='data.Country'),
        ),
        migrations.AddField(
            model_name='cryptoexchange',
            name='currencies',
            field=models.ManyToManyField(blank=True, related_name='exchange_currencies', to='data.Currency'),
        ),
        migrations.AddField(
            model_name='cryptoexchange',
            name='tickers',
            field=models.ManyToManyField(blank=True, related_name='exchange_tickers', to='crypto.Cryptocurrency'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_coin', to='crypto.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_source', to='crypto.cryptoexchange'),
        ),
        migrations.AddField(
            model_name='amounts',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_watchlist', to='crypto.cryptowatchlist'),
        ),
    ]
