# Generated by Django 4.0 on 2022-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
